services:
  discord-bot:
    build: .
    # specify which files you want in the container so that .env is not copied
    volumes:
      - ./src/main.py:/app/main.py
      - ./requirements.txt:/app/requirements.txt

    env_file:
      - .env

    environment:
      - DISCORD_TOKEN
